console.log("Hi, this is console screen");
var first="Arya";
var second="Chatrath";
var full=first.concat(second);
console.log(full);
console.log(first+second);
var length=first.length;
console.log(length);
var sentence="Hi, this is Arya.";
var replace=sentence.replace("Arya","Arya Chatrath");
console.log(replace);
var capital="ARYA";
var lowercase=capital.toLowerCase();
console.log(lowercase);
var small="arya";
var big=small.toUpperCase();
console.log(big);
var maximum=Math.max(1,2,3,4,5,6,7,8,9,0);
console.log(maximum);
var minimum=Math.min(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18);
console.log(minimum);
var big=100.7867856785678;
var fix=big.toFixed(2);
console.log(fix);
var num1=5;
var num2=6;
console.log(num1+num2);
var x="2";
var y="3";
console.log(x+y);
var a=10;
a++;
a++;
var b=2;
b--;
console.log(b);
var d="he";
var f="she";
var h=d.concat(f)
console.log(h)
var number1=3;
var number2=2;
console.log(number1+number2);
console.log(number1/number2);
console.log(number1*number2);
console.log(number1-number2);
